### ISSUE TITLE
r733, Texplorer no DLC autotoc + lack of Progress bar/debug output

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#180]
So, good news is that issue #144 is fixed. Texplorer is no longer hanging when it runs into PCCs that aren't selected, and then hits DLCs. The textures are getting replaced, and all user-specified PCCs modded

But, two new issues:

**1. DLC is not being TOC'd.**
It should be autotoc'd, and it's not being TOC'd at all. The base game is, but DLC is not.

**2. Progress bar and Debug Output.**
This no longer fills green to indicate completion. It also isn't providing any TOC-related output at all. Not for the base game (which was TOC'd) or the DLC (which was not TOC'd).

![texplorer_dlctoc](https://cloud.githubusercontent.com/assets/13645804/13035555/2de1e412-d308-11e5-9980-4becd05bd363.PNG)

**Comment by KFreon** [comment]
Fixed progress bar and stuff.
Pretty sure I fixed the TOCing too.

**Comment by ghost** [comment]
Progress bar is now great. Says when it's TOCing :)

However, it's not TOCing DLC, even when replacing a DLC texture. It TOCs the base game, but after that the debug says "No extracted DLC. Not TOCing." and DLC are not TOCed.

**Comment by KFreon** [comment]
That meddling __metadata folder again.

**Comment by ghost** [comment]
Ha. Yeah, I was wondering if all of these pathing and TOCing issues were due to the same couple of things :)

**Comment by ghost** [comment]
TOCing issue still not fixed. DLC are not TOCed upon replacing a texture, similar to #266.

**Comment by ghost** [comment]
Yay, fixed! DLCs now TOC upon texture replace.

Verified in rev748.
